# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-kz2OPUD3YgTNdLjKyyFBuB0DQNG_-j
"""



list=[int(i) for i in input("enter the values:").split() ]
list.sort()
list.reverse()
print(list)