# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xueZUQf2SIkHx6yuRxfhIvhj09NnCQrS
"""

x=int(input("enter list size"))
lst=[]
print("enter list elements")
for i in range(0,x):
  ele = int(input())

  lst.append(ele)
     
lst1=[]
for i in range(1,x+1):
  lst1.append(lst.index(i))

res = [x+1 for x in lst1]
print(res)