# -*- coding: utf-8 -*-
"""final_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16k3S2iAAtsnAcSCfdtm3O6-C6T1zmld3
"""

'''
celsius to fahrenheit converter

'''

celsius = float(input("Enter temperature in celsius: "))
fahrenheit = (celsius * 9/5) + 32
print('%f degree Celsius is: %f degree Fahrenheit' %(celsius, fahrenheit))