# -*- coding: utf-8 -*-
"""Day2_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-kz2OPUD3YgTNdLjKyyFBuB0DQNG_-j
"""

## Project: OTP Generator
import random as r
import string
length = 6
otp = ''
characters = string.ascii_letters + string.digits
print(characters)

for i in range(length):
  otp = otp + r.choice(characters)

print("OTP:", otp)