# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-kz2OPUD3YgTNdLjKyyFBuB0DQNG_-j
"""

mylist = [1, 2, 1, 4, 1, 2]
r_item = 1

for item in mylist:
	if(item==r_item):
		mylist.remove(r_item)

print(mylist)