# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-kz2OPUD3YgTNdLjKyyFBuB0DQNG_-j
"""

import string
inputString = input("Enter the string : ")
allAlphabets = 'abcdefghijklmnopqrstuvwxyz'
flag = 0
for char in allAlphabets:
    if char not in inputString.lower():
        flag = 1
if flag == 1:
    print("This is not a pangram string");
else:
    print("It is a pangram string")